### ISSUE TITLE
Description doesn't show...

### ISSUE THREAD

**Issue by kprkpr** [pulsejet/banner-ics#1]
Hi!
I was searching a ics simple viewer for roundcube, and I saw your plugin, installed, and seens to work, but I recieved and ICS that outlook sees, but roundcube not.. I saw that the description is in a "DESCRIPTION:" line, and has a html alternative using "X-ALT-DESC"
I attach the ics (With mails and url changed)
[icsfile.zip](https://github.com/pulsejet/banner-ics/files/5573896/icsfile.zip)

In roundcube shows an exclamation (I think is searching other field as description and not found..)
![image](https://user-images.githubusercontent.com/5132053/99807792-488c7d00-2b40-11eb-93e4-ac596db51d62.png)
And email is in blank

If you can help/fix it...
Thanks!

**Comment by pulsejet** [comment]
* You're seeing the exclamation mark because of the Larry theme (this plugin was built to support only elastic). AFAIK, Larry doesn't have any CSS class to remove the exclamation mark.
* We don't show the description of the event. If you want to add it, you can do so manually (or maybe make a backward compatible PR to make this configurable) by editing the php file around here https://github.com/pulsejet/banner-ics/blob/b8bf26c59dc3802a6dde45aca5f2976b2eecf107/banner_ics.php#L96

**Comment by pulsejet** [comment]
@kprkpr the warning box won't show up on Larry now

**Comment by kprkpr** [comment]
Oh
Thanks!
Will see about the description, sorry for not answering
